# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  gen:
    dao:
      - link: "mysql:root:12345678@tcp(localhost:3306)/freekey_admin"
        tables: ""
        removePrefix: "s_,u_,c_,w_"
        descriptionTag: true
        noModelComment: true
        group: "sys"
        clear: true
        overwriteDao: true