server:
  name: "FREE KEY"
  address: ":2033"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  serverRoot: "resource/public"
  dumpRouterMap: true
  routeOverWrite: true
  jwtExpireDuration: "7D" # 7 days
  imgPrefix: "http://localhost:2033/upload" # 图片前缀
  rootFilePath: "/resource/public/upload/"  # 文件上传路径
  rootIp: "localhost"
  wsUrl: "ws://localhost:2033/admin/sys/ws"
  clientMaxBodySize: "200MB"

logger:
  path: "logs/default"
  level: "all"
  stdout: true

# Database.
database:
  logger:
    level: "all"
    stdout: true
  sys:
    link: "mysql:root:12345678@tcp(localhost:3306)/freekey_admin?loc=Local&parseTime=true"
    debug: true
redis:
  default:
    address: "localhost:6379"
    db: 1
    pass: ""
